name: PRIMEXARMY Bot Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python Libraries
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Build PRIMEX Binary
        run: |
          # EAGLE.c ki jagah ab PRIMEXARMY.c use ho raha hai
          gcc PRIMEXARMY.c -o PRIMEXARMY -pthread
          chmod +x PRIMEXARMY

      - name: Start PRIMEXARMY Bot
        run: python PRIMEXARMY.py
